obj-$(CONFIG_BATTERY_SAMSUNG)	+= sec_battery.o
obj-$(CONFIG_OF)		+= sec_adc.o
obj-$(CONFIG_MULTI_CHARGING)	+= sec_multi_charger.o
obj-$(CONFIG_MULTI_PORT_CHARGING)	+= sec_multi_port_charger.o
obj-$(CONFIG_STEP_CHARGING)	+= sec_step_charging.o
obj-$(CONFIG_BATTERY_CISD)	+= sec_cisd.o
obj-$(CONFIG_BATTERY_NOTIFIER)	+= battery_notifier.o

obj-$(CONFIG_FUELGAUGE_SM5708)		+= sm5708_fuelgauge.o
obj-$(CONFIG_CHARGER_SM5708)	+= sm5708_charger.o sm5708_charger_oper.o

