dtb-$(CONFIG_MACH_J8Y18LTE_SWA_INS) += sdm450-sec-j8y18lte_swa_ins-r00.dtb \
					sdm450-sec-j8y18lte_swa_ins-r01.dtb \
					sdm450-sec-j8y18lte_swa_ins-r02.dtb \
					sdm450-sec-j8y18lte_swa_ins-r03.dtb
					
always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
