ifeq ($(CONFIG_BUILD_ARM64_DT_OVERLAY),y)
dtbo-$(CONFIG_ARCH_ZQL1695) += samsung-sdm439-qrd-r00-default-overlay.dtbo \
	samsung-sdm439-qrd-r01-overlay.dtbo \
	samsung-sdm439-qrd-r02-overlay.dtbo \
	samsung-sdm439-qrd-r03-overlay.dtbo \
	samsung-sdm439-qrd-r04-overlay.dtbo \
	samsung-sdm439-qrd-r05-overlay.dtbo \
	samsung-sdm439-qrd-r06-overlay.dtbo \
	samsung-sdm439-qrd-r07-overlay.dtbo \
	samsung-sdm439-qrd-r08-overlay.dtbo \
	samsung-sdm439-qrd-r09-overlay.dtbo

samsung-sdm439-qrd-r01-overlay.dtbo-base := sdm439.dtb \
	msm8937-interposer-sdm439.dtb
samsung-sdm439-qrd-r02-overlay.dtbo-base := sdm439.dtb \
	msm8937-interposer-sdm439.dtb
samsung-sdm439-qrd-r03-overlay.dtbo-base := sdm439.dtb \
	msm8937-interposer-sdm439.dtb
samsung-sdm439-qrd-r04-overlay.dtbo-base := sdm439.dtb \
	msm8937-interposer-sdm439.dtb
samsung-sdm439-qrd-r05-overlay.dtbo-base := sdm439.dtb \
	msm8937-interposer-sdm439.dtb
samsung-sdm439-qrd-r06-overlay.dtbo-base := sdm439.dtb \
	msm8937-interposer-sdm439.dtb
samsung-sdm439-qrd-r07-overlay.dtbo-base := sdm439.dtb \
	msm8937-interposer-sdm439.dtb
samsung-sdm439-qrd-r08-overlay.dtbo-base := sdm439.dtb \
	msm8937-interposer-sdm439.dtb
samsung-sdm439-qrd-r09-overlay.dtbo-base := sdm439.dtb \
	msm8937-interposer-sdm439.dtb

# HS70 code added by tangqingyong for HS70-9 at 20191002 start
# HS70 code added by tangqingyong for HS70-11 at 20191003 start
dtbo-$(CONFIG_ARCH_ZQL1871) += samsung-sdm450-qrd-r00-default-overlay.dtbo \
	samsung-sdm450-qrd-r01-overlay.dtbo \
	samsung-sdm450-qrd-r02-overlay.dtbo \
	samsung-sdm450-qrd-r03-overlay.dtbo \
	samsung-sdm450-qrd-r04-overlay.dtbo \
	samsung-sdm450-qrd-r05-overlay.dtbo \
	samsung-sdm450-qrd-r06-overlay.dtbo \
	samsung-sdm450-qrd-r07-overlay.dtbo \
	samsung-sdm450-qrd-r08-overlay.dtbo \
	samsung-sdm450-qrd-r09-overlay.dtbo

samsung-sdm450-qrd-r00-default-overlay.dtbo-base := sdm450.dtb \
	sdm450-pmi632.dtb \
	msm8953.dtb
samsung-sdm450-qrd-r01-overlay.dtbo-base := sdm450.dtb \
	sdm450-pmi632.dtb \
	msm8953.dtb
samsung-sdm450-qrd-r02-overlay.dtbo-base := sdm450.dtb \
	sdm450-pmi632.dtb \
	msm8953.dtb
samsung-sdm450-qrd-r03-overlay.dtbo-base := sdm450.dtb \
	sdm450-pmi632.dtb \
	msm8953.dtb
samsung-sdm450-qrd-r04-overlay.dtbo-base := sdm450.dtb \
	sdm450-pmi632.dtb \
	msm8953.dtb
samsung-sdm450-qrd-r05-overlay.dtbo-base := sdm450.dtb \
	sdm450-pmi632.dtb \
	msm8953.dtb
samsung-sdm450-qrd-r06-overlay.dtbo-base := sdm450.dtb \
	sdm450-pmi632.dtb \
	msm8953.dtb
samsung-sdm450-qrd-r07-overlay.dtbo-base := sdm450.dtb \
	sdm450-pmi632.dtb \
	msm8953.dtb
samsung-sdm450-qrd-r08-overlay.dtbo-base := sdm450.dtb \
	sdm450-pmi632.dtb \
	msm8953.dtb
samsung-sdm450-qrd-r09-overlay.dtbo-base := sdm450.dtb \
	sdm450-pmi632.dtb \
	msm8953.dtb
# HS70 code added by tangqingyong for HS70-11 at 20191003 end
# HS70 code added by tangqingyong for HS70-9 at 20191002 end
else
dtb-$(CONFIG_ARCH_MSM8937) += msm8937-pmi8950-mtp.dtb \
	msm8937-interposer-sdm439-cdp.dtb \
	msm8937-interposer-sdm439-mtp.dtb \
	msm8937-interposer-sdm439-qrd.dtb \
	msm8937-interposer-sdm429-cdp.dtb \
	msm8937-interposer-sdm429-mtp.dtb

dtb-$(CONFIG_ARCH_SDM439) += sdm439-mtp.dtb \
	sdm439-cdp.dtb \
	sdm439-qrd.dtb \
	sda439-mtp.dtb \
	sda439-cdp.dtb \
	sdm439-external-codec-mtp.dtb \
	sdm439-rcm.dtb \
	qm215-qrd.dtb \
	qm215-qrd-smb1360.dtb

dtb-$(CONFIG_ARCH_SDM429) += sdm429-mtp.dtb \
	sdm429-cdp.dtb \
	sdm429-qrd.dtb \
	sda429-mtp.dtb \
	sda429-cdp.dtb \
	sdm429-qrd-spyro-evt.dtb
	
dtb-$(CONFIG_MACH_J8Y18LTE_CIS_SER) += sdm450-sec-j8y18lte_cis_ser-r00.dtb \
					sdm450-sec-j8y18lte_cis_ser-r01.dtb \
					sdm450-sec-j8y18lte_cis_ser-r02.dtb \
					sdm450-sec-j8y18lte_cis_ser-r03.dtb
					
dtb-$(CONFIG_MACH_J8Y18LTE_SWA_OPEN) += sdm450-sec-j8y18lte_swa_open-r00.dtb \
					sdm450-sec-j8y18lte_swa_open-r01.dtb \
					sdm450-sec-j8y18lte_swa_open-r02.dtb \
					sdm450-sec-j8y18lte_swa_open-r03.dtb
					
dtb-$(CONFIG_MACH_J8Y18LTE_SWA_INS) += sdm450-sec-j8y18lte_swa_ins-r00.dtb \
					sdm450-sec-j8y18lte_swa_ins-r01.dtb \
					sdm450-sec-j8y18lte_swa_ins-r02.dtb \
					sdm450-sec-j8y18lte_swa_ins-r03.dtb

dtb-$(CONFIG_MACH_J8Y18LTE_LTN_OPEN) += sdm450-sec-j8y18lte_ltn_open-r00.dtb \
					sdm450-sec-j8y18lte_ltn_open-r01.dtb \
					sdm450-sec-j8y18lte_ltn_open-r02.dtb \
					sdm450-sec-j8y18lte_ltn_open-r03.dtb
					
dtb-$(CONFIG_MACH_J8Y18LTE_MEA_JV) += sdm450-sec-j8y18lte_mea_jv-r00.dtb \
					sdm450-sec-j8y18lte_mea_jv-r01.dtb \
					sdm450-sec-j8y18lte_mea_jv-r02.dtb \
					sdm450-sec-j8y18lte_mea_jv-r03.dtb

dtb-$(CONFIG_MACH_J8Y18LTE_SEA_OPEN) += sdm450-sec-j8y18lte_sea_open-r00.dtb \
					sdm450-sec-j8y18lte_sea_open-r01.dtb \
					sdm450-sec-j8y18lte_sea_open-r02.dtb \
					sdm450-sec-j8y18lte_sea_open-r03.dtb

endif

dtb-$(CONFIG_ARCH_SDM845_VM) += sdm845-vm.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
